"""A pure-asyncio OpenTelemetry OTLP client."""

from otlp_client.client import OTLPClient, __version__
from otlp_client.config import Compression, OTLPConfig, OTLPProtocol
from otlp_client.errors import (
    OTLPConfigError,
    OTLPError,
    OTLPPermanentError,
    OTLPTransportError,
)
from otlp_client.model.common import AnyValue, InstrumentationScope, Resource
from otlp_client.model.logs import (
    LOG_RECORD_FLAGS_TRACE_FLAGS_MASK,
    LogRecord,
    ResourceLogs,
    ScopeLogs,
    SeverityNumber,
    log_record,
)
from otlp_client.model.metrics import (
    DATA_POINT_FLAGS_NO_RECORDED_VALUE,
    AggregationTemporality,
    Buckets,
    ExponentialHistogram,
    ExponentialHistogramDataPoint,
    Gauge,
    Histogram,
    HistogramDataPoint,
    Metric,
    NumberDataPoint,
    ResourceMetrics,
    ScopeMetrics,
    Sum,
    Summary,
    SummaryDataPoint,
    ValueAtQuantile,
    data_point_flags,
    gauge,
    sum_,
)
from otlp_client.model.traces import (
    SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE,
    SPAN_FLAGS_CONTEXT_IS_REMOTE,
    SPAN_FLAGS_TRACE_FLAGS_MASK,
    ResourceSpans,
    ScopeSpans,
    Span,
    SpanEvent,
    SpanKind,
    SpanLink,
    Status,
    StatusCode,
    span,
    span_flags,
)
from otlp_client.outcomes import ExportOutcome, PartialSuccess, Permanent, Retryable, Success
from otlp_client.processor import BatchProcessor, ProcessorStats
from otlp_client.signals import SignalKind

__all__ = [
    "DATA_POINT_FLAGS_NO_RECORDED_VALUE",
    "LOG_RECORD_FLAGS_TRACE_FLAGS_MASK",
    "SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE",
    "SPAN_FLAGS_CONTEXT_IS_REMOTE",
    "SPAN_FLAGS_TRACE_FLAGS_MASK",
    "AggregationTemporality",
    "AnyValue",
    "BatchProcessor",
    "Buckets",
    "Compression",
    "ExponentialHistogram",
    "ExponentialHistogramDataPoint",
    "ExportOutcome",
    "Gauge",
    "Histogram",
    "HistogramDataPoint",
    "InstrumentationScope",
    "LogRecord",
    "Metric",
    "NumberDataPoint",
    "OTLPClient",
    "OTLPConfig",
    "OTLPConfigError",
    "OTLPError",
    "OTLPPermanentError",
    "OTLPProtocol",
    "OTLPTransportError",
    "PartialSuccess",
    "Permanent",
    "ProcessorStats",
    "Resource",
    "ResourceLogs",
    "ResourceMetrics",
    "ResourceSpans",
    "Retryable",
    "ScopeLogs",
    "ScopeMetrics",
    "ScopeSpans",
    "SeverityNumber",
    "SignalKind",
    "Span",
    "SpanEvent",
    "SpanKind",
    "SpanLink",
    "Status",
    "StatusCode",
    "Success",
    "Sum",
    "Summary",
    "SummaryDataPoint",
    "ValueAtQuantile",
    "__version__",
    "data_point_flags",
    "gauge",
    "log_record",
    "span",
    "span_flags",
    "sum_",
]
